// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXyUN2eqGKpsc_PKOQbjf1D2SaboASP0o',
    appId: '1:1062424246141:android:ceb16d1af8bf5047d77e14',
    messagingSenderId: '1062424246141',
    projectId: 'winnersend',
    storageBucket: 'winnersend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2ruJ6mjVs_MDMCJS6WDnuCqDtcG_d3hI',
    appId: '1:1062424246141:ios:2deba296b0155c52d77e14',
    messagingSenderId: '1062424246141',
    projectId: 'winnersend',
    storageBucket: 'winnersend.firebasestorage.app',
    androidClientId: '1062424246141-chk1n6i58eoa83ps0ugquvm9ondd9pv4.apps.googleusercontent.com',
    iosClientId: '1062424246141-qep2r0m3ak3lj3iqrfmrqt1865e18mrk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

}